### ISSUE TITLE
I'd love to use this plug-in, but unfortunately it doesn't work on php7.3rc6.

### ISSUE THREAD

**Issue by finip** [o10n-x/wordpress-file-page-cache#14]
//errors code
url:
http://localhost:8086/wp-admin/plugins.php?activate=true&plugin_status=all&paged=1&s=
code:
`PHP Fatal error:  Uncaught Error: Call to a member function add_notice() on null in G:\w\w\f\wp-content\plugins\wordpress-file-page-cache\core\controllers\error.class.php:60
Stack trace:
#0 G:\w\w\f\wp-content\plugins\wordpress-file-page-cache\core\controllers\core.class.php(215): O10n\Error->handle(Object(O10n\Exception))
#1 G:\w\w\f\wp-content\plugins\wordpress-file-page-cache\core\controllers\exception.class.php(48): O10n\Core::forward_exception(Object(O10n\Exception))
#2 G:\w\w\f\wp-content\plugins\wordpress-file-page-cache\core\controllers\file.class.php(55): O10n\Exception->__construct('Cache directory...', 'core')
#3 G:\w\w\f\wp-content\plugins\wordpress-file-page-cache\core\controllers\controller.class.php(134): O10n\File->setup()
#4 G:\w\w\f\wp-content\plugins\wordpress-file-page-cache\core\controllers\file.class.php(34): O10n\Controller::construct(Object(O10n\Core), Array)
#5 G:\w\w\f\wp-content\plugins\wordpress-file-page-cache\core\controllers\core.class.php(194): O10n\File::load(Object(O10n\Core))
#6 G:\w\w\f\wp-c in G:\w\w\f\wp-content\plugins\wordpress-file-page-cache\core\controllers\error.class.php on line 60`
I hope I can get your help, because I've been studying opcache optimization recently.

**Comment by optimalisatie** [comment]
The bug has been fixed in `v0.0.42`. Thanks again for reporting the issue!

**Comment by finip** [comment]
Thank you very much for your detailed reply. I just downloaded and installed the package again, and I encountered a new error.
//errors code
url:
http://localhost:8086/wp-admin/plugins.php?activate=true&plugin_status=all&paged=1&s=
code:
`PHP Fatal error:  Uncaught Error: Call to a member function get() on null in G:\w\w\f\wp-content\plugins\wordpress-file-page-cache\core\controllers\env.class.php:204
Stack trace:
#0 G:\w\w\f\wp-content\plugins\wordpress-file-page-cache\core\controllers\error.class.php(63): O10n\Env->is_debug()
#1 G:\w\w\f\wp-content\plugins\wordpress-file-page-cache\core\controllers\core.class.php(215): O10n\Error->handle(Object(O10n\Exception))
#2 G:\w\w\f\wp-content\plugins\wordpress-file-page-cache\core\controllers\exception.class.php(48): O10n\Core::forward_exception(Object(O10n\Exception))
#3 G:\w\w\f\wp-content\plugins\wordpress-file-page-cache\core\controllers\file.class.php(55): O10n\Exception->__construct('Cache directory...', 'core')
#4 G:\w\w\f\wp-content\plugins\wordpress-file-page-cache\core\controllers\controller.class.php(134): O10n\File->setup()
#5 G:\w\w\f\wp-content\plugins\wordpress-file-page-cache\core\controllers\file.class.php(34): O10n\Controller::construct(Object(O10n\Core), Array)
#6 G:\w\w\f\wp-content\plugins\wordpre in G:\w\w\f\wp-content\plugins\wordpress-file-page-cache\core\controllers\env.class.php on line 204`
I hope I can continue to get your help.
